[project]
name = "agns-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "orjson>=3.11.6",
    "pydantic>=2.12.5",
    "uvicorn[standard]>=0.40.0",
    "uvloop>=0.22.1",
]
